export const SET_FAVORITE_COMMUNITY = "SET_FAVORITE_COMMUNITY";
export const ADD_FAVORITE_COMMUNITY = "ADD_FAVORITE_COMMUNITY";
export const REMOVE_FAVORITE_COMMUNITY = "REMOVE_FAVORITE_COMMUNITY";
export const CHANGE_STATE_FAVORITE_COMMUNITY = "CHANGE_STATE_FAVORITE_COMMUNITY";
