export const CREATE_COMMUNITY = "CREATE_COMMUNITY";
export const CHANGE_COMMUNITY_NAME = "CHANGE_COMMUNITY_NAME";
export const CHANGE_COMMUNITY_DESCRIPTION = "CHANGE_COMMUNITY_DESCRIPTION";
export const TOGGLE_PRIVATE_STATUS = "TOGGLE_PRIVATE_STATUS";
export const SET_PRIVATE_STATUS = "SET_PRIVATE_STATUS";
export const CHANGE_START_DATE = "CHANGE_START_DATE";
export const CHANGE_END_DATE = "CHANGE_END_DATE";
