export const SET_CURRENT_COMMUNITY = "SET_CURRENT_COMMUNITY";
export const CHANGE_CURRENT_COMMUNITY_STATE = "CHANGE_CURRENT_COMMUNITY_STATE";
export const SET_COMMUNITY_USERS = "SET_COMMUNITY_USERS";
export const ADD_COMMUNITY_USERS = "ADD_COMMUNITY_USERS";
export const CHANGE_COMMUNITY_DESCRIPTION = "CHANGE_COMMUNITY_DESCRIPTION";
