export const SET_CONFIRM_MESSAGE_BOX = "SET_CONFIRM_MESSAGE_BOX";
export const SET_CONFIRM_MESSAGE_TXT = "SET_CONFIRM_MESSAGE_TXT";
export const SET_CONFIRM_MESSAGE_FEED_ID = "SET_CONFIRM_MESSAGE_FEED_ID";
export const SET_CONFIRM_MESSAGE_FEED_ACTION = "SET_CONFIRM_MESSAGE_FEED_ACTION";
