export const SET_TODAYS_COMMUNITY = "SET_TODAYS_COMMUNITY";
export const ADD_TODAYS_COMMUNITY = "ADD_TODAYS_COMMUNITY";
export const REMOVE_FROM_TODAYS_COMMUNITY = "REMOVE_FROM_TODAYS_COMMUNITY";
export const CHANGE_STATE_TODAYS_COMMUNITY = "CHANGE_STATE_TODAYS_COMMUNITY";
