export const SET_MY_COMMUNITY = "SET_MY_COMMUNITY";
export const ADD_MY_COMMUNITY = "ADD_MY_COMMUNITY";
export const DELETE_MY_COMMUNITY = "DELETE_MY_COMMUNITY";
export const CHANGE_STATE_MY_COMMUNITY = "CHANGE_STATE_MY_COMMUNITY";

