export const SET_ALL_COMMUNITY = "SET_ALL_COMMUNITY";
export const ADD_ALL_COMMUNITY = "ADD_ALL_COMMUNITY";
export const DELETE_FROM_ALL_COMMUNITY = "DELETE_FROM_ALL_COMMUNITY";
export const CHANGE_STATE_ALL_COMMUNITY = "CHANGE_STATE_ALL_COMMUNITY";
export const SET_ALL_COMMUNITY_STATUS = "SET_ALL_COMMUNITY_STATUS";
